FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

COPY server/package*.json server/
RUN npm run install-server --omit=dev 
COPY client/package*.json client/
RUN npm run install-client  


COPY client/ client/
RUN npm run build-client  

COPY server/ server/

USER node

CMD [ "npm", "start", "--prefix", "server" ]

EXPOSE 8000